version: '3'
services:
  backend:
    build: ./backend
    ports:
      - '8000:8000'
    env_file:
      - .env
  neo4j:
    image: neo4j:5
    environment:
      - NEO4J_AUTH=neo4j/test
    ports:
      - '7474:7474'
      - '7687:7687'
